### ISSUE TITLE
[Bug] this.getData is not a function

### ISSUE THREAD

**Issue by leonardpauli** [mlc-ai/web-llm-chat#30]
### Bug Description

Got this crash multiple times for a bit. Now not reproducing, but possibly related to parsing/rendering code blocks?

Also, only "clear all data" is available as a recourse... Could be nice to at least allow me to attempt download prev chats before?

### Steps to Reproduce

1. Make llm generate a code block
2. Sometimes receive crash

### Expected Behavior

No crash.

### Screenshots

<img width="633" alt="Screenshot 2024-06-05 at 21 32 34" src="https://github.com/mlc-ai/web-llm-chat/assets/1329834/42976c8a-5fb4-4cc4-b4a5-798878ebaf67">

### Desktop Browser

Chrome

### Desktop Browser Version

124?

**Comment by X-MQSI** [comment]
I met it, too. It's a terrible problem ...

**Comment by Neet-Nestor** [comment]
To help me better reproduce, could you let me know which model are you using to generate code blocks?

**Comment by Neet-Nestor** [comment]
This problem seems to be caused by the `remark-gfm` markdown plugin. After updating it from v3.0.1 to v4.0.0, the problem seems resolved for me.

https://github.com/mlc-ai/web-llm-chat/commit/6a98181bf14f5924b6c524c5d22d905b0a356c94

**Comment by Neet-Nestor** [comment]
@leonardpauli @X-MQSI 

Please let me know if this fixed the issue on your end.

**Comment by Neet-Nestor** [comment]
Closed as the issue seems resolved. Please reopen the issue any time if anyone met the same issue again.
